### ISSUE TITLE
How to build QUD Windows driver version 1.00.94.2?

### ISSUE THREAD

**Issue by pengchengyang** [qualcomm/qcom-usb-kernel-drivers#79]
Visual Studio 2022 succeed to build 1.00.91.6 but failed to build 1.00.94.2
Steps:
1. Open the path "HY11\QMI\win\qcwwan\wdfserial", then open "qcwdfserial.sln" with Visual Studio 2022 build it.
2. Build successfully with 1.00.91.6 and output "HY11\QMI\win\qcwwan\wdfserial\x64\Debug\qcwdfserial.sys".
3. Failed to build with 1.00.94.2 and output error "QCRD. c (540,82): error C2039: "SessionTotal": not a member of "_QCVNet""

**Comment by 5656hcx** [comment]
Hi @pengchengyang 

`HY11\QMI\win\qcwwan\wdfserial` is not part of our repository.

I just tried building the branch https://github.com/qualcomm/qcom-usb-kernel-drivers/tree/release-win-1.00.94.2 with Visual Studio 2022, it works without any compilation errors. Please make sure the local branch is exactly the same as remote, and also make sure all the required dependencies are installed.

Also, for Visual Studio 2022 and later, you may need to specify `SHA256` in `Project Property -> Driver Signing -> General -> File Digest Algorithm`. We have add this in the latest code but not `1.00.94.2` branch.

If the issue persists, please share full log of the build output. Thanks.

Best,
Chenxi
